version: '3.7'

#service template
x-mongodb:
  &mongodb
  image: mongo:4.2
    labels:
      docker.service: mongodb
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - /data/mongodb/db:/data/db
      - /data/mongodb/mongod.conf:/etc/mongod.conf
      - /data/mongodb/keyfile:/etc/mongodb/keyfile
      - /root/certs/hostname:/etc/mongodb/cert
    deploy:
      mode: replicated
      replicas: 1
    command: --config /etc/mongod.conf

#service instances
services:
  rs0:
    <<: *mongodb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.rs == 0
  rs1:
    <<: *mongodb
    deploy:
      placement:
        constraints:
          - node.labels.mongo.rs == 1
  rs2:
    <<: *mongodb
    deploy:
      placement:
        constraints:
          - node.labels.mongo.rs == 2
